services:
  crimsoncf:
    container_name: crimsoncf
    image: docker.io/amirzx/crimsoncf:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SERVE_STATIC=1
    restart: unless-stopped
